### ISSUE TITLE
Linux connection difficulty and simple fix

### ISSUE THREAD

**Issue by pughb** [smilg/rigol-data-collector#1]
I'm not sure if anyone was running into this, but I was finding that I wasn't able to connect to the scope at first on linux. After reading some VISA library documentation , it turns out that for pyvisa-py (or ni-visa) to work over USB, you need to reload udev rules, which I did by logging in and logging out - now it works!

**Comment by smilg** [comment]
[Added a note to the README](https://github.com/smilg/rigol-data-collector/commit/8913e79b7927dec2b46ad5f8c70d1a8636accb70) - thanks for the heads up!
